config/routes.rb
Rails.application.routes.draw do
  resources :domino_messages

  resources :names_entries

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :domino_servers do
    member do
      post "load_names_entry"
      post "tail"
    end

  end

    get "session/new"
  post "session/create"
  delete "session/destroy"
  get "session/destroy"

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'home#index'
  get 'home/locks'
  get 'home/test_domino_message_data'



  get 'flot' => 'home#flot'
  get 'morris' => 'home#morris'
  get 'tables' => 'home#tables'
  get 'forms' => 'home#forms'

  get 'panels_wells' => 'home#panels_wells'
  get 'buttons' => 'home#buttons'
  get 'notifications' => 'home#notifications'
  get 'typography' => 'home#typography'
  get 'grid' => 'home#grid'
  get 'blank' => 'home#blank'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/names_entry.rb
# == Schema Information
#
# Table name: names_entries
#
#  id               :integer          not null, primary key
#  domino_server_id :integer
#  cn               :string(255)
#  lastname         :string(255)
#  firstname        :string(255)
#  mailserver       :string(255)
#  email            :string(255)
#  level0           :string(255)
#  level1           :string(255)
#  level2           :string(255)
#  level3           :string(255)
#  level4           :string(255)
#  uid              :string(255)
#  displayname      :string(255)
#  status           :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class NamesEntry < ActiveRecord::Base
  # include Mongoid::Document
  #
  # field :cn
  # field :firstname
  # field :lastname
  # field :email
  # field :mailserver
  # field :level0
  # field :level1
  # field :level2
  # field :level3
  # field :uid
  # field :displayname
  # field :status

  belongs_to :domino_server
end

app/controllers/names_entries_controller.rb
class NamesEntriesController < ApplicationController
  before_action :set_names_entry, only: [:show, :edit, :update, :destroy]

  # GET /names_entries
  # GET /names_entries.json
  def index
    @names_entries = NamesEntry.all
  end

  # GET /names_entries/1
  # GET /names_entries/1.json
  def show
  end

  # GET /names_entries/new
  def new
    @names_entry = NamesEntry.new
  end

  # GET /names_entries/1/edit
  def edit
  end

  # POST /names_entries
  # POST /names_entries.json
  def create
    @names_entry = NamesEntry.new(names_entry_params)

    respond_to do |format|
      if @names_entry.save
        format.html { redirect_to @names_entry, notice: 'Names entry was successfully created.' }
        format.json { render :show, status: :created, location: @names_entry }
      else
        format.html { render :new }
        format.json { render json: @names_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names_entries/1
  # PATCH/PUT /names_entries/1.json
  def update
    respond_to do |format|
      if @names_entry.update(names_entry_params)
        format.html { redirect_to @names_entry, notice: 'Names entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @names_entry }
      else
        format.html { render :edit }
        format.json { render json: @names_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names_entries/1
  # DELETE /names_entries/1.json
  def destroy
    @names_entry.destroy
    respond_to do |format|
      format.html { redirect_to names_entries_url, notice: 'Names entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_names_entry
      @names_entry = NamesEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def names_entry_params
      params.require(:names_entry).permit(:server_id, :cn, :lastname, :firstname, :mailserver, :email, :level0, :level1, :level2, :level3, :level4, :uid, :displayname, :status)
    end
end

app/helpers/names_entries_helper.rb
module NamesEntriesHelper
end

app/views/names_entries/_form.html.haml
= form_for @names_entry do |f|
  - if @names_entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@names_entry.errors.count, "error")} prohibited this names_entry from being saved:"
      %ul
        - @names_entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :server_id
    = f.text_field :server_id
  .field
    = f.label :cn
    = f.text_field :cn
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :mailserver
    = f.text_field :mailserver
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :level0
    = f.text_field :level0
  .field
    = f.label :level1
    = f.text_field :level1
  .field
    = f.label :level2
    = f.text_field :level2
  .field
    = f.label :level3
    = f.text_field :level3
  .field
    = f.label :level4
    = f.text_field :level4
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :displayname
    = f.text_field :displayname
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/names_entries/edit.html.haml
%h1 Editing names_entry

= render 'form'

= link_to 'Show', @names_entry
\|
= link_to 'Back', names_entries_path

app/views/names_entries/index.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Names Entry
      / /.panel-heading
      .panel-body
        .table-responsive
          %table#dataTables-example.table.table-striped.table-bordered.table-hover
            %thead
              %tr
                %th Server
                %th Level0
                %th Email
                %th Displayname
                %th Action

            %tbody
              - @names_entries.each do |names_entry|
                %tr.odd.gradeX
                  %td= names_entry.domino_server_id
                  %td= names_entry.level0
                  %td= names_entry.email
                  %td= names_entry.displayname
                  %td
                    =link_to names_entry, class: "", title: "Show" do
                      %i.fa.fa-search.fa-fw
                    =link_to edit_names_entry_path(names_entry), class: "", title: "Edit" do
                      %i.fa.fa-pencil.fa-fw
                    =link_to names_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "" , title: "Destroy" do
                      %i.fa.fa-trash-o.fa-fw
        / /.table-responsive
/ Page-Level Demo Scripts - Tables - Use for reference
:javascript
  $(document).ready(function() {
      $('#dataTables-example').dataTable();
  });

app/views/names_entries/new.html.haml
%h1 New names_entry

= render 'form'

= link_to 'Back', names_entries_path

app/views/names_entries/show.html.haml
%p#notice= notice

%p
  %b Server:
  = @names_entry.server_id
%p
  %b Cn:
  = @names_entry.cn
%p
  %b Lastname:
  = @names_entry.lastname
%p
  %b Firstname:
  = @names_entry.firstname
%p
  %b Mailserver:
  = @names_entry.mailserver
%p
  %b Email:
  = @names_entry.email
%p
  %b Level0:
  = @names_entry.level0
%p
  %b Level1:
  = @names_entry.level1
%p
  %b Level2:
  = @names_entry.level2
%p
  %b Level3:
  = @names_entry.level3
%p
  %b Level4:
  = @names_entry.level4
%p
  %b Uid:
  = @names_entry.uid
%p
  %b Displayname:
  = @names_entry.displayname
%p
  %b Status:
  = @names_entry.status

= link_to 'Edit', edit_names_entry_path(@names_entry)
\|
= link_to 'Back', names_entries_path