config/routes.rb
Rails.application.routes.draw do
  resources :domino_messages

  resources :names_entries

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :domino_servers do
    member do
      post "load_names_entry"
      post "tail"
    end

  end

    get "session/new"
  post "session/create"
  delete "session/destroy"
  get "session/destroy"

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'home#index'
  get 'home/locks'
  get 'home/test_domino_message_data'



  get 'flot' => 'home#flot'
  get 'morris' => 'home#morris'
  get 'tables' => 'home#tables'
  get 'forms' => 'home#forms'

  get 'panels_wells' => 'home#panels_wells'
  get 'buttons' => 'home#buttons'
  get 'notifications' => 'home#notifications'
  get 'typography' => 'home#typography'
  get 'grid' => 'home#grid'
  get 'blank' => 'home#blank'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    detail=domino_message_data
    @chart1_data={chart_data: detail.to_json}
    detail=domino_message_detail_by_message_type
    @chart2_data={chart_data: detail["IN"].to_json}
    @chart3_data={chart_data: detail["OUT"].to_json}
    detail=domino_message_detail_by_domain
    @chart4_data={chart_data: detail["OUT"].to_json}
    @chart5_data={chart_data: detail["IN"].to_json}
    detail=domino_message_history
    @chart6_data={chart_data: detail.to_json}





    respond_to do |format|
      format.html

    end
  end





  def live_data
    now=Time.now.advance(minutes: -5, :seconds=>Time.now.utc_offset).at_beginning_of_minute

    if params[:type]=="2"
      @data=[]
      d1=now.advance(minutes: -(now.min % 5))# arrotonda all'ultimo blocco da 5 minuti
      d0=d1.advance(minutes:-5) #5 minuti prima
      t0=(d1.to_i)*1000 #adesso in millisecondi
      @data[0]=[t0, Message.where(data:  Date.today, message_type: MESSAGE_TYPE_IN_INTERNET).where(["time between :d0 and :d1", d0: d0, d1: d1]).count("*")] #"Ricevuti"
      @data[1]=[t0, Message.where(data:  Date.today, message_type: MESSAGE_TYPE_OUT_INTERNET).where(["time between :d0 and :d1", d0: d0, d1: d1]).count("*") ]  #"Inviati"
      @data[2]=[t0, Message.where(data:  Date.today, message_type: (MESSAGE_TYPE_IN_CAMERA+MESSAGE_TYPE_OUT_CAMERA)).where(["time between :d0 and :d1", d0: d0, d1: d1]).count("*")] #"Interni camera"
      @data[3]=[t0, Message.where(data:  Date.today, message_type: (MESSAGE_TYPE_IN_SENATO+MESSAGE_TYPE_OUT_SENATO)).where(["time between :d0 and :d1", d0: d0, d1: d1]).count("*")] #"Interni senato"
      puts @data.inspect
      render json: @data
      return
    #elsif params[:type]=="3"
    #  @data=[]
    #  d1=now.advance(minutes: -(now.min % 5))  # arrotonda all'ultimo blocco da 5 minuti
    #  #d1=Time.now.advance(minutes: -(Time.now.min % 5)).at_beginning_of_minute  # arrotonda all'ultimo blocco da 5 minuti
    #  groups={}
    #  Group.where(group_type: params[:gt]).each{|g| groups[g.group_name]||=[] if !g.group_name.blank? ; groups[g.group_name]<<g.element if !g.group_name.blank?}
    #  @data << Message.where(data:  Date.today, to_type: groups[params[:t1]], message_type: MESSAGE_TYPE_IN_INTERNET).where(["time <= :d1", d1: d1]).count("*")
    #  @data << Message.where(data:  Date.today, from_type: groups[params[:f1]]).where(["time <= :d1", d1: d1]).count("*")
    #  @data<<=Message.where(data:  Date.today, to_type: groups[params[:t2]], message_type: MESSAGE_TYPE_IN_INTERNET).where(["time <= :d1", d1: d1]).count("*")
    #  @data<<=Message.where(data:  Date.today, from_type: groups[params[:f2]]).where(["time <= :d1", d1: d1]).count("*")
    #
    #
    #  render json: @data
    #  return
    elsif params[:type]=="4"
      @data=[]
      d1=now.advance(minutes: -(now.min % 5))  # arrotonda all'ultimo blocco da 5 minuti
      gt=params[:gt]

      params[:data].each do |k,data|

        if true
          count=Message.where(data:  Date.today)
          data[:filters].each do |kk,f|
            if f[:name]=="to_type"
              xx= Group.where(group_type: gt, group_name: f[:value]).map(&:element)
              count=count.where(to_type: xx)
            elsif f[:name]=="from_type"
              xx= Group.where(group_type: gt, group_name: f[:value]).map(&:element)
              count=count.where(from_type: xx)
            elsif f[:name]=="message_type"
              count=count.where(message_type: f[:value])
            else
              puts "#### NON GESTITO"
            end
          end
          @data << [data[:name], count.count]
        end
      end
      render json: @data
      return
    else
        d0=(now.to_i)*1000
        @data=[]
        @data[0]=[d0, Message.where(data:  Date.today, message_type: MESSAGE_TYPE_IN_INTERNET).count("*")] #"Ricevuti"
        @data[1]=[d0, Message.where(data:  Date.today, message_type: MESSAGE_TYPE_OUT_INTERNET).count("*") ]  #"Inviati"
        @data[2]=[d0, Message.where(data:  Date.today, message_type: (MESSAGE_TYPE_IN_CAMERA+MESSAGE_TYPE_OUT_CAMERA)).count("*")] #"Interni camera"
        @data[3]=[d0, Message.where(data:  Date.today, message_type: (MESSAGE_TYPE_IN_SENATO+MESSAGE_TYPE_OUT_SENATO)).count("*")] #"Interni senato"
        render json: @data
      return
      end



  end

  def domino_message_data

    now=Time.now.advance(:seconds=>Time.now.utc_offset).at_beginning_of_minute
    start_time=now.advance(minutes: -360)
    result={}
    tot={"IN"=>0, "OUT"=>0}

    #sql=["Select distinct  message_type from domino_messages where date > ?", start_time]
    #message_types=DominoMessage.find_by_sql(sql).map{|x| x.message_type}


    sql=["Select message_type , count(*) as tot from domino_messages where date >= ? and date < ? group by message_type", start_time.at_beginning_of_day, start_time]
    DominoMessage.find_by_sql(sql).each do |r|
      tot[r.message_type]=r.tot
    end

    sql=["Select extract(hour from date) as h , extract(minute from date) as m,  message_type,
        count(*) as tot from domino_messages where date > ?
        group by extract(hour from date) , extract(minute from date), message_type
        order by extract(hour from date) , extract(minute from date)", start_time]


    DominoMessage.find_by_sql(sql).each do |r|

      key_data=Date.today.to_time.advance(hours: (r.h+2), minutes: r.m).to_i*1000

      tot.keys.each do |t|
        tot[t] += r.tot if t==r.message_type
        if r.m%15==0
          result[key_data] ||= {}
          result[key_data][t]=tot[t]
        end
      end

      #puts [r.h, r.m, r.tot, r.message_type, tot[r.message_type]].inspect   if r.message_type=="OUT - forwarded"
      #puts "#{key_data} #{result[key_data].inspect}"
      #message_types.push r.message_type unless message_types.include?(r.message_type)
    end

    array=tot.keys.map{|t|
      {label: t.to_s,
       data: result.map{|k,v| [k, v[t].to_i]}
      }
    }


    return array

    #respond_to do |format|
    #    format.html { render text: @domino_message_data}
    #    format.json { render json: @domino_message_data}
    #end
  end
  def domino_message_history

      #IERI
      result={}
      array=[]
      tot={"IN"=>0, "OUT"=>0}
      -7.upto(0).each do |i|
      start_time=Date.today.advance(days: i)
      tot={"IN"=>0, "OUT"=>0}
      #sql=["Select message_type , count(*) as tot from domino_messages where date >= ? and date < ? group by message_type", start_time.at_beginning_of_day, start_time]
      #DominoMessage.find_by_sql(sql).each do |r|
      #  tot[r.message_type]=0
      #end

      sql=["Select extract(hour from date) as h ,  message_type ,
        count(*) as tot from domino_messages where date >= ? and date <= ?
        group by extract(hour from date) , message_type
        order by extract(hour from date) ", start_time.at_beginning_of_day, start_time.at_end_of_day]

      DominoMessage.find_by_sql(sql).each do |r|
        key_data=start_time.at_beginning_of_day.advance(hours: (r.h+2)).to_i*1000
        tot.keys.each do |t|
          tot[t] += r.tot if t==r.message_type
            result[key_data] ||= {}
            result[key_data][t]=tot[t]
        end
      end

      end
      array += tot.keys.map{|t|
        {label: "#{t.to_s}",
         data: result.map{|k,v| [k, v[t].to_i]}
        }
      }
    return array
  end
  def domino_message_detail_by_message_type
    start_time=Date.today
    result={}
    tot={}
    domino_message_detail={}
    ["IN","OUT"].each do |message_type|
    sql=["Select  message_subtype , count(*) as tot from domino_messages where message_type=? and date >= ?
        group by message_subtype",message_type, start_time]
    domino_message_detail[message_type]=DominoMessage.find_by_sql(sql).map{|r| {label:r.message_subtype, data:r.tot}}
    end
    return domino_message_detail
  end

  def domino_message_detail_by_domain
    start_time=Date.today
    result={}
    tot={}
    domino_message_detail={}
    sql=["Select  domain_from , count(*) as tot from domino_messages where message_type='IN' and date >= ?
       group by domain_from order by count(*) desc", start_time]
    domino_message_detail["IN"]=[]
    counter=0
    DominoMessage.find_by_sql(sql).each do |r|
      counter +=1
      if counter < 6
        domino_message_detail["IN"] << {label:"#{r.domain_from}", data:r.tot}
      else
        x=domino_message_detail["IN"].last
        x[:label]="Other Domains"
        x[:data] ||=0
        x[:data] += r.tot
      end
    end

    sql=["Select  domain_to , count(*) as tot from domino_messages where message_type='OUT' and date >= ?
        group by domain_to order by count(*) desc", start_time]
    counter=0
    domino_message_detail["OUT"]=[]
    DominoMessage.find_by_sql(sql).each do |r|
      counter +=1
      if counter < 6
        domino_message_detail["OUT"] << {label:"#{r.domain_to}",  data:r.tot}
      else
        x=domino_message_detail["OUT"].last
        x[:label]="Other Domains"
        x[:data] ||=0
        x[:data] += r.tot
      end
    end


    return domino_message_detail
  end

  def test_domino_message_data
    @domino_message_detail=domino_message_history
    respond_to do |format|
        format.html { render text: @domino_message_detail}
        format.json { render json: @domino_message_detail}
    end
  end



  def live_mail_relay

    #subj=EximLog.where(date: Date.today).group("subject")
    result={inviate: {}, ricevute:{}}

    base_search=EximLog.where("1=1")
    params[:search_date_from]||=Date.today
    params[:search_date_to]||=Date.today

    base_search = base_search.where(["date >= ?", params[:search_date_from]])
    base_search = base_search.where(["date <= ?", params[:search_date_to]])

    base_search = base_search.where(["mail_from like ?", params[:search_mail_from]]) unless params[:search_mail_from].blank?

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dropdown_messages.haml
-@messages.each do |n|
  %li
    %a{:href => "#"}
      %div
        %strong=n.label
        %span.pull-right.text-muted
          %em=time_ago_in_words(n.updated_at)
        %div=n.description
%li.divider
%li
  %a.text-center{:href => "#"}
    %strong Read All Messages
    %i.fa.fa-angle-right
/ /.dropdown-messages

app/views/home/_dropdown_tasks.haml
%li
  %a{:href => "#"}
    %div
      %p
        %strong Archiving
        %span.pull-right.text-muted 40% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progressbar", :style => "width: 40%"}
          %span.sr-only 40% Complete (success)
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 2
        %span.pull-right.text-muted 20% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
          %span.sr-only 20% Complete
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 3
        %span.pull-right.text-muted 60% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 60%"}
          %span.sr-only 60% Complete (warning)
%li.divider
%li
  %a{:href => "#"}
    %div
      %p
        %strong Task 4
        %span.pull-right.text-muted 80% Complete
      .progress.progress-striped.active
        .progress-bar.progress-bar-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
          %span.sr-only 80% Complete (danger)
%li.divider
%li
  %a.text-center{:href => "#"}
    %strong See All Tasks
    %i.fa.fa-angle-right
/ /.dropdown-tasks

app/views/home/_side_menu.haml
%li
  =link_to root_path do
    %i.fa.fa-dashboard.fa-fw
    Dashboard
%li
  %a{:href => "#"}
    %i.fa.fa-bar-chart-o.fa-fw
    Charts
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "flot.html"} Flot Charts
    %li
      %a{:href => "morris.html"} Morris.js Charts
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-bar-chart-o.fa-fw
    Domino Servers
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      =link_to "List", domino_servers_path
    %li
      =link_to "Add New", new_domino_server_path
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-bar-chart-o.fa-fw
    Users
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      =link_to "Users", names_entries_path

  / /.nav-second-level
%li
  %a{:href => "/tables.html"}
    %i.fa.fa-table.fa-fw
    Tables
%li
  %a{:href => "/forms.html"}
    %i.fa.fa-edit.fa-fw
    Forms
%li
  %a{:href => "#"}
    %i.fa.fa-wrench.fa-fw
    UI Elements
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "/panels_wells.html"} Panels and Wells
    %li
      %a{:href => "/buttons.html"} Buttons
    %li
      %a{:href => "/notifications.html"} Notifications
    %li
      %a{:href => "/typography.html"} Typography
    %li
      %a{:href => "/grid.html"} Grid
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-sitemap.fa-fw
    Multi-Level Dropdown
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"}
        Third Level
        %span.fa.arrow
      %ul.nav.nav-third-level
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
      / /.nav-third-level
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-files-o.fa-fw
    Sample Pages
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "blank.html"} Blank Page
    %li
      %a{:href => "login.html"} Login Page
  / /.nav-second-level
/ /#side-menu

app/views/home/_top_menu.haml
%li
  =link_to root_path do
    %i.fa.fa-dashboard.fa-fw
    Dashboard
%li
  =link_to domino_servers_path do
    Domino Servers
    %i.fa.fa-bar-chart-o.fa-fw
%li
  =link_to names_entries_path do
    Names Entries
    %i.fa.fa-bar-chart-o.fa-fw
  / /.nav-second-level
%li
  %a{:href => "/tables.html"}
    %i.fa.fa-table.fa-fw
    Tables
%li
  %a{:href => "/forms.html"}
    %i.fa.fa-edit.fa-fw
    Forms
%li
  %a{:href => "#"}
    %i.fa.fa-wrench.fa-fw
    UI Elements
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "/panels_wells.html"} Panels and Wells
    %li
      %a{:href => "/buttons.html"} Buttons
    %li
      %a{:href => "/notifications.html"} Notifications
    %li
      %a{:href => "/typography.html"} Typography
    %li
      %a{:href => "/grid.html"} Grid
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-sitemap.fa-fw
    Multi-Level Dropdown
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"} Second Level Item
    %li
      %a{:href => "#"}
        Third Level
        %span.fa.arrow
      %ul.nav.nav-third-level
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
        %li
          %a{:href => "#"} Third Level Item
      / /.nav-third-level
  / /.nav-second-level
%li
  %a{:href => "#"}
    %i.fa.fa-files-o.fa-fw
    Sample Pages
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      %a{:href => "blank.html"} Blank Page
    %li
      %a{:href => "login.html"} Login Page
  / /.nav-second-level
/ /#side-menu

app/views/home/blank.haml
.row
  .col-lg-12
    %h1.page-header Blank

app/views/home/buttons.haml
.row
  .col-lg-12
    %h1.page-header Buttons
  / /.col-lg-12
/ /.row
.row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Default Buttons
      / /.panel-heading
      .panel-body
        %h4 Normal Buttons
        %p
          %button.btn.btn-default{:type => "button"} Default
          %button.btn.btn-primary{:type => "button"} Primary
          %button.btn.btn-success{:type => "button"} Success
          %button.btn.btn-info{:type => "button"} Info
          %button.btn.btn-warning{:type => "button"} Warning
          %button.btn.btn-danger{:type => "button"} Danger
          %button.btn.btn-link{:type => "button"} Link
        %br
          %h4 Disabled Buttons
          %p
            %button.btn.btn-default.disabled{:type => "button"} Default
            %button.btn.btn-primary.disabled{:type => "button"} Primary
            %button.btn.btn-success.disabled{:type => "button"} Success
            %button.btn.btn-info.disabled{:type => "button"} Info
            %button.btn.btn-warning.disabled{:type => "button"} Warning
            %button.btn.btn-danger.disabled{:type => "button"} Danger
            %button.btn.btn-link.disabled{:type => "button"} Link
          %br
            %h4 Button Sizes
            %p
              %button.btn.btn-primary.btn-lg{:type => "button"} Large button
              %button.btn.btn-primary{:type => "button"} Default button
              %button.btn.btn-primary.btn-sm{:type => "button"} Small button
              %button.btn.btn-primary.btn-xs{:type => "button"} Mini button
              %br
                %br
                  %button.btn.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
    / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Circle Icon Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Normal Circle Buttons
        %button.btn.btn-default.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-primary.btn-circle{:type => "button"}
          %i.fa.fa-list
        %button.btn.btn-success.btn-circle{:type => "button"}
          %i.fa.fa-link
        %button.btn.btn-info.btn-circle{:type => "button"}
          %i.fa.fa-check
        %button.btn.btn-warning.btn-circle{:type => "button"}
          %i.fa.fa-times
        %button.btn.btn-danger.btn-circle{:type => "button"}
          %i.fa.fa-heart
        %br
          %br
            %h4 Large Circle Buttons
            %button.btn.btn-default.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-check
            %button.btn.btn-primary.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-list
            %button.btn.btn-success.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-link
            %button.btn.btn-info.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-check
            %button.btn.btn-warning.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-times
            %button.btn.btn-danger.btn-circle.btn-lg{:type => "button"}
              %i.fa.fa-heart
            %br
              %br
                %h4 Extra Large Circle Buttons
                %button.btn.btn-default.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-check
                %button.btn.btn-primary.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-list
                %button.btn.btn-success.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-link
                %button.btn.btn-info.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-check
                %button.btn.btn-warning.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-times
                %button.btn.btn-danger.btn-circle.btn-xl{:type => "button"}
                  %i.fa.fa-heart
      / /.panel-body
    / /.panel
  / /.col-lg-6
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Outline Buttons with Smooth Transition
      / /.panel-heading
      .panel-body
        %h4 Outline Buttons
        %p
          %button.btn.btn-outline.btn-default{:type => "button"} Default
          %button.btn.btn-outline.btn-primary{:type => "button"} Primary
          %button.btn.btn-outline.btn-success{:type => "button"} Success
          %button.btn.btn-outline.btn-info{:type => "button"} Info
          %button.btn.btn-outline.btn-warning{:type => "button"} Warning
          %button.btn.btn-outline.btn-danger{:type => "button"} Danger
          %button.btn.btn-outline.btn-link{:type => "button"} Link
        %br
          %h4 Outline Button Sizes
          %p
            %button.btn.btn-outline.btn-primary.btn-lg{:type => "button"} Large button
            %button.btn.btn-outline.btn-primary{:type => "button"} Default button
            %button.btn.btn-outline.btn-primary.btn-sm{:type => "button"} Small button
            %button.btn.btn-outline.btn-primary.btn-xs{:type => "button"} Mini button
            %br
              %br
                %button.btn.btn-outline.btn-primary.btn-lg.btn-block{:type => "button"} Block level button
    / /.panel-body
    / /.panel
    .panel.panel-default
      .panel-heading
        Social Buttons with Font Awesome Icons
      / /.panel-heading
      .panel-body
        %h4 Social Buttons
        %a.btn.btn-block.btn-social.btn-bitbucket
          %i.fa.fa-bitbucket
          Sign in with Bitbucket
        %a.btn.btn-block.btn-social.btn-dropbox
          %i.fa.fa-dropbox
          Sign in with Dropbox
        %a.btn.btn-block.btn-social.btn-facebook
          %i.fa.fa-facebook
          Sign in with Facebook
        %a.btn.btn-block.btn-social.btn-flickr
          %i.fa.fa-flickr
          Sign in with Flickr
        %a.btn.btn-block.btn-social.btn-github
          %i.fa.fa-github
          Sign in with GitHub
        %a.btn.btn-block.btn-social.btn-google-plus
          %i.fa.fa-google-plus
          Sign in with Google
        %a.btn.btn-block.btn-social.btn-instagram
          %i.fa.fa-instagram
          Sign in with Instagram
        %a.btn.btn-block.btn-social.btn-linkedin
          %i.fa.fa-linkedin
          Sign in with LinkedIn
        %a.btn.btn-block.btn-social.btn-pinterest
          %i.fa.fa-pinterest
          Sign in with Pinterest
        %a.btn.btn-block.btn-social.btn-tumblr
          %i.fa.fa-tumblr
          Sign in with Tumblr
        %a.btn.btn-block.btn-social.btn-twitter
          %i.fa.fa-twitter
          Sign in with Twitter
        %a.btn.btn-block.btn-social.btn-vk
          %i.fa.fa-vk
          Sign in with VK
        %hr
          .text-center
            %a.btn.btn-social-icon.btn-bitbucket
              %i.fa.fa-bitbucket
            %a.btn.btn-social-icon.btn-dropbox
              %i.fa.fa-dropbox
            %a.btn.btn-social-icon.btn-facebook
              %i.fa.fa-facebook
            %a.btn.btn-social-icon.btn-flickr
              %i.fa.fa-flickr
            %a.btn.btn-social-icon.btn-github
              %i.fa.fa-github
            %a.btn.btn-social-icon.btn-google-plus
              %i.fa.fa-google-plus
            %a.btn.btn-social-icon.btn-instagram
              %i.fa.fa-instagram
            %a.btn.btn-social-icon.btn-linkedin
              %i.fa.fa-linkedin
            %a.btn.btn-social-icon.btn-pinterest
              %i.fa.fa-pinterest
            %a.btn.btn-social-icon.btn-tumblr
              %i.fa.fa-tumblr
            %a.btn.btn-social-icon.btn-twitter
              %i.fa.fa-twitter
            %a.btn.btn-social-icon.btn-vk
              %i.fa.fa-vk
      / /.panel-body
    / /.panel
  / /.col-lg-6
/ /.row

app/views/home/locks.html.haml
.row
  .col-lg-12
    %h1.page-header Locks
  / /.col-lg-12
/ /.row
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Domino Locks
      / /.panel-heading
      .panel-body
        .table-responsive
          %table#lock-table.table.table-striped.table-bordered.table-hover
            %thead
              %tr
                %th Server
                %th lock Date
                %th Database Name
                %th Lock Mode
                %th TotalLocks

            %tbody
              -@locks.each do |k,v|
                -v.each do |l|
                  %tr
                    %td=l.domino_server.name
                    %td=l.date
                    %td=l.database_name
                    %td=l.lock_type
                    %td=v.size




:javascript
  $(document).ready(function() {
      $('#lock-table').dataTable();
  });