config/routes.rb
Rails.application.routes.draw do
  resources :domino_messages

  resources :names_entries

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :domino_servers do
    member do
      post "load_names_entry"
      post "tail"
    end

  end

    get "session/new"
  post "session/create"
  delete "session/destroy"
  get "session/destroy"

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'home#index'
  get 'home/locks'
  get 'home/test_domino_message_data'



  get 'flot' => 'home#flot'
  get 'morris' => 'home#morris'
  get 'tables' => 'home#tables'
  get 'forms' => 'home#forms'

  get 'panels_wells' => 'home#panels_wells'
  get 'buttons' => 'home#buttons'
  get 'notifications' => 'home#notifications'
  get 'typography' => 'home#typography'
  get 'grid' => 'home#grid'
  get 'blank' => 'home#blank'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/domino_message.rb
# == Schema Information
#
# Table name: domino_messages
#
#  id               :integer          not null, primary key
#  date             :datetime
#  domino_server_id :integer
#  messageid        :string(255)
#  notes_message_id :string(255)
#  mail_from        :string(255)
#  mail_to          :string(255)
#  size             :integer
#  smtp_from        :string(255)
#  mail_relay       :string(255)
#  forward_by_rule  :string(255)
#  message_type     :string(255)
#  subject          :string(255)
#  notes            :text
#  created_at       :datetime
#  updated_at       :datetime
#  message_subtype  :string(255)
#  domain_from      :string(255)
#  domain_to        :string(255)
#

class DominoMessage < ActiveRecord::Base
  # include Mongoid::Document
  #
  # field :date,  type: Date
  # field :time,  type: Time
  # field :msgid,  type: String
  # field :mail_from,  type: String
  # field :mail_to,  type: String
  # field :size,  type: String
  # field :smtp_from,  type: String
  # field :mail_relay,  type: String
  # field :forward_by_rule,  type: String
  # field :message_type,  type: String
  # field :from_type,  type: String
  # field :to_type,  type: String
  # field :subject,  type: String
  # field :notes,  type: String
  # field :messageid,  type: String

  belongs_to :domino_server
  validates_uniqueness_of :notes_message_id, scope: [:domino_server_id, :date, :mail_from, :mail_to]

  def forwarded?
    if message_type =="OUT"
      # se e' in uscita il mail_from dovrebbe essere di un internal domains
      DOMINO_STAT_CONFIG[:internal_domains].each{|t|  return false if mail_from.downcase.end_with?(t)}
      return true # mail_from
    else #message_type=="IN"
      # se e' in ingresso il mail_to dovrebbe essere di un internal domains
      DOMINO_STAT_CONFIG[:internal_domains].each{|t|  return false if mail_to.downcase.end_with?(t)}
      return true # mail_from
    end
  end
  def internal?
    a=DOMINO_STAT_CONFIG[:internal_domains].map{|t|  mail_from.downcase.end_with?(t) }.include?(true)
    b=DOMINO_STAT_CONFIG[:internal_domains].map{|t|  mail_to.downcase.end_with?(t) }.include?(true)
    return a && b
  end
  def domain(value)
    return if value.blank?
    test=/\w+@[\w.-]+|\{(?:\w+, *)+\w+\}@[\w.-]+/
    if value.match(test)
      address=value.match(test)[0]
    else
      address=value
    end
    DOMINO_STAT_CONFIG[:internal_domains].each do |x|
      return DOMINO_STAT_CONFIG[:main_domain]  if address.downcase.end_with? x
    end

    case
      when /@/
        return address.split("@").last
      else
        return "other"
    end

  end
end

app/controllers/domino_messages_controller.rb
class DominoMessagesController < ApplicationController
  before_action :set_domino_message, only: [:show, :edit, :update, :destroy]

  # GET /domino_messages
  # GET /domino_messages.json
  def index
    @domino_messages = DominoMessage.all
  end

  # GET /domino_messages/1
  # GET /domino_messages/1.json
  def show
  end

  # GET /domino_messages/new
  def new
    @domino_message = DominoMessage.new
  end

  # GET /domino_messages/1/edit
  def edit
  end

  # POST /domino_messages
  # POST /domino_messages.json
  def create
    @domino_message = DominoMessage.new(domino_message_params)

    respond_to do |format|
      if @domino_message.save
        format.html { redirect_to @domino_message, notice: 'Domino message was successfully created.' }
        format.json { render :show, status: :created, location: @domino_message }
      else
        format.html { render :new }
        format.json { render json: @domino_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domino_messages/1
  # PATCH/PUT /domino_messages/1.json
  def update
    respond_to do |format|
      if @domino_message.update(domino_message_params)
        format.html { redirect_to @domino_message, notice: 'Domino message was successfully updated.' }
        format.json { render :show, status: :ok, location: @domino_message }
      else
        format.html { render :edit }
        format.json { render json: @domino_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domino_messages/1
  # DELETE /domino_messages/1.json
  def destroy
    @domino_message.destroy
    respond_to do |format|
      format.html { redirect_to domino_messages_url, notice: 'Domino message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domino_message
      @domino_message = DominoMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domino_message_params
      params.require(:domino_message).permit(:date, :time, :domino_server_id, :messageid, :notes_message_id, :mail_from, :mail_to, :size, :smtp_from, :mail_relay, :forward_by_rule, :message_type, :subject, :notes)
    end
end

app/helpers/domino_messages_helper.rb
module DominoMessagesHelper
end

app/views/domino_messages/_form.html.haml
= form_for @domino_message do |f|
  - if @domino_message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@domino_message.errors.count, "error")} prohibited this domino_message from being saved:"
      %ul
        - @domino_message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :time
    = f.time_select :time
  .field
    = f.label :domino_server_id
    = f.number_field :domino_server_id
  .field
    = f.label :messageid
    = f.text_field :messageid
  .field
    = f.label :notes_message_id
    = f.text_field :notes_message_id
  .field
    = f.label :mail_from
    = f.text_field :mail_from
  .field
    = f.label :mail_to
    = f.text_field :mail_to
  .field
    = f.label :size
    = f.number_field :size
  .field
    = f.label :smtp_from
    = f.text_field :smtp_from
  .field
    = f.label :mail_relay
    = f.text_field :mail_relay
  .field
    = f.label :forward_by_rule
    = f.text_field :forward_by_rule
  .field
    = f.label :message_type
    = f.text_field :message_type
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/domino_messages/edit.html.haml
%h1 Editing domino_message

= render 'form'

= link_to 'Show', @domino_message
\|
= link_to 'Back', domino_messages_path

app/views/domino_messages/index.html.haml
%h1 Listing domino_messages

%table
  %tr
    %th Date
    %th Time
    %th Domino server
    %th Messageid
    %th Notes message
    %th Mail from
    %th Mail to
    %th Size
    %th Smtp from
    %th Mail relay
    %th Forward by rule
    %th Message type
    %th Subject
    %th Notes
    %th
    %th
    %th

  - @domino_messages.each do |domino_message|
    %tr
      %td= domino_message.date
      %td= domino_message.time
      %td= domino_message.domino_server_id
      %td= domino_message.messageid
      %td= domino_message.notes_message_id
      %td= domino_message.mail_from
      %td= domino_message.mail_to
      %td= domino_message.size
      %td= domino_message.smtp_from
      %td= domino_message.mail_relay
      %td= domino_message.forward_by_rule
      %td= domino_message.message_type
      %td= domino_message.subject
      %td= domino_message.notes
      %td= link_to 'Show', domino_message
      %td= link_to 'Edit', edit_domino_message_path(domino_message)
      %td= link_to 'Destroy', domino_message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Domino message', new_domino_message_path

app/views/domino_messages/new.html.haml
%h1 New domino_message

= render 'form'

= link_to 'Back', domino_messages_path

app/views/domino_messages/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @domino_message.date
%p
  %b Time:
  = @domino_message.time
%p
  %b Domino server:
  = @domino_message.domino_server_id
%p
  %b Messageid:
  = @domino_message.messageid
%p
  %b Notes message:
  = @domino_message.notes_message_id
%p
  %b Mail from:
  = @domino_message.mail_from
%p
  %b Mail to:
  = @domino_message.mail_to
%p
  %b Size:
  = @domino_message.size
%p
  %b Smtp from:
  = @domino_message.smtp_from
%p
  %b Mail relay:
  = @domino_message.mail_relay
%p
  %b Forward by rule:
  = @domino_message.forward_by_rule
%p
  %b Message type:
  = @domino_message.message_type
%p
  %b Subject:
  = @domino_message.subject
%p
  %b Notes:
  = @domino_message.notes

= link_to 'Edit', edit_domino_message_path(@domino_message)
\|
= link_to 'Back', domino_messages_path