config/routes.rb
Rails.application.routes.draw do
  resources :domino_messages

  resources :names_entries

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :domino_servers do
    member do
      post "load_names_entry"
      post "tail"
    end

  end

    get "session/new"
  post "session/create"
  delete "session/destroy"
  get "session/destroy"

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'home#index'
  get 'home/locks'
  get 'home/test_domino_message_data'



  get 'flot' => 'home#flot'
  get 'morris' => 'home#morris'
  get 'tables' => 'home#tables'
  get 'forms' => 'home#forms'

  get 'panels_wells' => 'home#panels_wells'
  get 'buttons' => 'home#buttons'
  get 'notifications' => 'home#notifications'
  get 'typography' => 'home#typography'
  get 'grid' => 'home#grid'
  get 'blank' => 'home#blank'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/domino_server.rb
# == Schema Information
#
# Table name: domino_servers
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  ip            :string(255)
#  ldap_port     :string(255)
#  ldap_ssl      :boolean
#  ldap_username :string(255)
#  ldap_password :string(255)
#  ldap_treebase :string(255)
#  ldap_hostname :string(255)
#  ldap_filter   :string(255)
#  ssh_user      :string(255)
#  ssh_password  :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  tail_status   :string(255)
#  enabled_tail  :boolean
#  enabled_auth  :boolean
#

class DominoServer < ActiveRecord::Base
  # include Mongoid::Document
  # field :name, type: String
  # field :ip, type: String
  # field :ldap_port, type: String
  # field :ldap_ssl, type: String
  # field :ldap_username, type: String
  # field :ldap_password, type: BSON::Binary
  # field :ldap_treebase, type: String
  # field :ldap_hostname, type: String
  # field :ldap_filter, type: String
  # field :ssh_user, type: String
  # field :ssh_password, type: BSON::Binary



  has_many :names_entries
  has_many :domino_messages
  has_many :domino_connections
  has_many :domino_locks

  attr_encrypted :ldap_pwd, :key => "secret_key", :attribute => 'ldap_password'
  attr_encrypted :ssh_pwd, :key => "secret_key", :attribute => 'ssh_password'

  scope :enabled_for_auth, where(:enabled_auth => true)
  scope :enabled_for_tail, where(:enabled_tail => true)


  def log_message(match_data, type)

    data={}
    match_data.names.each {|k| data[k.to_sym]=match_data[k]}
    message_date = DateTime.parse(data[:datetime])
    message_type=nil
    message_subtype=nil



    case type
      when :smtp_received
        #TODO - put in cache and update message_id usind notes msgid
        #@message=@server.log_message($LAST_MATCH_INFO, :smtp_received)
        #domino_messages.build(date: $~[:date], time: $~[:time], notes_message_id: $~[:msgid], messageid: $~[:messageid], smtp_from: $~[:smtp_from], size: $~[:size])
      when :msg_delivered
          message_type="IN"
          message=DominoMessage.new(domino_server_id: self.id, date: message_date ,notes_message_id: data[:msgid] ,mail_to: data[:mail_to], mail_from: data[:mail_from], size: data[:size])
      when :msg_forwarded
        message=DominoMessage.new(domino_server_id: self.id,date: message_date,notes_message_id: data[:msgid] , mail_to: data[:mail_to], mail_from: data[:mail_from])
          message_type="OUT"
          message_subtype="forwarded"
      when :msg_auto_forwarded
        message=DominoMessage.new(domino_server_id: self.id,date: message_date,notes_message_id: data[:msgid] , mail_to: data[:mail_to], mail_from: data[:mail_from])
          message_type="OUT"
          message_subtype="auto-forwarded"
      when :msg_transferred
          message_type="OUT"
          message=DominoMessage.new(domino_server_id: self.id,date: message_date,notes_message_id: data[:msgid] , mail_to: data[:mail_to], mail_from: data[:mail_from], mail_relay: data[:mail_relay], size: data[:size])
    end

    if message
    # monitored= [data[:mail_from],data[:mail_to]].map do |x|
    #   x=x.downcase
    #   DOMINO_STAT_CONFIG[:monitored_domains].map{|t|  x.end_with?(t) ? 1 : 0 }.sum
    # end.sum  if data[:mail_from]
    message.message_type=message_type
    message.domain_from=message.domain(message.mail_from)
    message.domain_to=message.domain(message.mail_to)

    message_subtype||="forwarded" if message.forwarded?
    message_subtype||="internal"  if message.internal?
    message_subtype||="generic"


    message.message_subtype=message_subtype
    message.save
    end
    message
  end



  def log_lock(match_data, type, date)
    data={}
    match_data.names.each {|k| data[k.to_sym]=match_data[k]}
    message_date = date
    dbname=data[:dbname].split("/").last
    @message=self.domino_locks.build(date: message_date, database_name: dbname , lock_type: data[:mode])
    @message.save
    counter=self.domino_locks.where(["domino_locks.date >= :date1 and domino_locks.date < :date2 and domino_locks.database_name=:database", date1: Date.today, date2: Date.tomorrow, database: dbname]).count

    log_notification(dbname, "#{counter} locks", counter, counter) if counter > 100 #TODO gestire il limite

  end

  def log_connection(match_data, type)
    data={}
    match_data.names.each {|k| data[k.to_sym]=match_data[k]}
    data[:user] ||= data[:ip_address]
    data[:action] ||= type.to_s
    message_date = DateTime.parse(data[:datetime])

    self.domino_connections.create(date: message_date,action: data[:action] , ip: data[:ip_address], user: data[:user])

    counter=self.domino_connections.where(["domino_connections.date >= :date1 and domino_connections.date < :date2 and domino_connections.ip=:ip", date1: Date.today, date2: Date.tomorrow, ip: data[:ip_address]]).count

    log_notification(data[:ip], "#{counter} Connection", counter, 100) if counter > 100 #TODO gestire il limite

    #@message=self.domino_connections.build()
    #@message.save
  end

  def log_notification(label, description, value, level)
    Notification.create(label: label, description: description, value: value, level: level, notification_type: "generic")

  end

  #todo transform to has_password :password_name_field, :key

  # def decrypt(field_name)
  #   #decrypted_value = Encryptor.decrypt(:value => self[field_name].data, :key => secret_key)
  #   decrypted_value = Encryptor.decrypt(:value => self.attribute(field_name), :key => secret_key)
  #   decrypted_value
  # end
  #
  # def ldap_password=(value)
  #   encrypted_value = Encryptor.encrypt(:value => value, :key => secret_key) unless value.blank?
  #   #self[:ldap_password]=BSON::Binary.new(encrypted_value)
  #   super(encrypted_value.encode('UTF-8'))
  # end
  #
  # def ssh_password=(value)
  #   encrypted_value = Encryptor.encrypt(:value => value, :key => secret_key) unless value.blank?
  #   #self[:ssh_password]=BSON::Binary.new(encrypted_value)
  #   super(encrypted_value.encode('UTF-8'))
  # end


  def import_contact_from_ldap(options={})#hostname, port, username, password, treebase="O=cameradep,C=IT")
    username=options[:username] || self.ldap_username
    password=options[:password] || self.ldap_pwd
    ldap=Net::LDAP.new(host: self.ldap_hostname,
                       port: self.ldap_port,
                       auth: {:method=> :simple,
                       username: username, password: password})
    ldap.encryption(:simple_tls) if self.ldap_port!="389"

    filter = Net::LDAP::Filter.construct(self.ldap_filter)
    found_ids=[]
    #MONGO
    self.names_entries.update_all(status: "cancelled")
    #ACTIVE RECORD

    ldap.search(:base => self.ldap_treebase, :filter => filter) do |entry|
      attrib={}
      attrib[:cn]=entry[:cn].last
      attrib[:firstname]=entry[:sn].last
      attrib[:lastname]=entry[:givenname].last
      attrib[:email]=entry[:mail].last
      attrib[:mailserver]=entry[:mailserver].last.to_s.downcase
      #if deleted[attrib[:server]].blank?
      # Account.update_all(server: attrib[:server], level0: 'cancellato')
      #  deleted[attrib[:server]]=true
      #end
      attrib[:level0]=entry[:level0].last
      attrib[:level1]=entry[:level1].last
      attrib[:level2]=entry[:level2].last
      attrib[:level3]=entry[:level3].last.gsub(/[!\W]/,"") if entry[:level3].last
      attrib[:uid]=entry[:uid].last
      attrib[:displayname]=entry[:displayname].last

      #unless entry[:email].blank?

      a=self.names_entries.where(email: attrib[:email]).first
      a||=self.names_entries.build(email: attrib[:email])
      a.attributes= attrib
      a.status="active"
      a.save

    end



  end

  def parse_line(line, options={})
    options[:datetime] ||= DateTime.now
    #TODO compose REGEXP
    domino_pid=/.{20}/

    log_timestamp=/(?<datetime>\d\d\/\d\d\/\d\d\d\d \d\d:\d\d:\d\d)/

    smtp_received=      /^#{domino_pid}#{log_timestamp}   SMTP Server: Message (?<msgid>.{8}) \(MessageID: (?<messageid>.*)\) received from (?<smtp_from>.*) size (?<size>\d*) bytes/
    msg_delivered=      /^#{domino_pid}#{log_timestamp}   Router: Message (?<msgid>.{8}|.{8}, .{8}) delivered to (?<mail_to>.*) from (?<mail_from>.*) .* .* Size: (?<size>.*) Time/
    msg_forwarded=      /^#{domino_pid}#{log_timestamp}   Router: Message (?<msgid>.{8}).* forwarded to (?<mail_to>.*) from (?<mail_from>.*) .* .*/
    msg_auto_forwarded= /^#{domino_pid}#{log_timestamp}   Router: Message (?<msgid>.{8}).* auto forwarded by (?<mail_from>.*) to (?<mail_to>.*)/
    msg_transferred=    /^#{domino_pid}#{log_timestamp}   Router: Message (?<msgid>.{8}).* transferred to (?<mail_relay>.*) for (?<mail_to>.*) from (?<mail_from>.*) .{10}:.{8} .{10}:.{8} Size: (?<size>.*) via SMTP/

    imap_connection=    /^#{domino_pid}#{log_timestamp}   IMAP Server: (?<ip_address>.*) (?<action>connected|disconnected)/
    imap_login=         /^#{domino_pid}#{log_timestamp}   IMAP Server: (?<user>.*) logged in from (?<ip_address>.*)/
    imap_logout=        /^#{domino_pid}#{log_timestamp}   IMAP Server: (?<user>.*) logged out/

    smtp_connected=     /^#{domino_pid}#{log_timestamp}   SMTP Server: (?<ip_address>.*) connected/
    smtp_disconnected=  /^#{domino_pid}#{log_timestamp}   SMTP Server: (?<ip_address>.*) disconnected. (?<messages>.*) message\[s\] received/

    smtp_login=         /^#{domino_pid}#{log_timestamp}   SMTP Server: Authentication succeeded for user (?<user>.*); connecting host (?<ip_address>.*)/
    smtp_login_error =  /^#{domino_pid}#{log_timestamp}   smtp: (?<username>.*) \[(?<ip>.*)\] authentication failure using internet password/
    smtp_mail_from_error =   /^#{domino_pid}#{log_timestamp}   SMTP Server: Message rejected. Authenticated user (?<username>.*) from host (?<ip>.*) sending mail from (?<err_mail_from>.*) failed to match directory address (?<mail_from>.*)/

app/controllers/domino_servers_controller.rb
class DominoServersController < ApplicationController
  before_action :set_domino_server, only: [:show, :edit, :update, :destroy]

  # GET /domino_servers
  # GET /domino_servers.json
  def index
    @domino_servers = DominoServer.all
  end

  # GET /domino_servers/1
  # GET /domino_servers/1.json
  def show
  end

  # GET /domino_servers/new
  def new
    @domino_server = DominoServer.new
  end

  # GET /domino_servers/1/edit
  def edit
  end

  # POST /domino_servers
  # POST /domino_servers.json
  def create
    @domino_server = DominoServer.new(domino_server_params)

    respond_to do |format|
      if @domino_server.save
        format.html { redirect_to @domino_server, notice: 'Domino server was successfully created.' }
        format.json { render :show, status: :created, location: @domino_server }
      else
        format.html { render :new }
        format.json { render json: @domino_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domino_servers/1
  # PATCH/PUT /domino_servers/1.json
  def update
    respond_to do |format|
      if @domino_server.update(domino_server_params)
        format.html { redirect_to @domino_server, notice: 'Domino server was successfully updated.' }
        format.json { render :show, status: :ok, location: @domino_server }
      else
        format.html { render :edit }
        format.json { render json: @domino_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domino_servers/1
  # DELETE /domino_servers/1.json
  def destroy
    @domino_server.destroy
    respond_to do |format|
      format.html { redirect_to domino_servers_url, notice: 'Domino server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /domino_servers
  # POST /domino_servers.json
  def load_names_entry
    set_domino_server
    @domino_server.import_contact_from_ldap
    respond_to do |format|
      format.html { redirect_to domino_servers_url, notice: 'Names Entry imported.' }
      format.json { head :no_content }
    end
  end

  # POST /domino_servers
  # POST /domino_servers.json
  def tail

    set_domino_server
    flag=@domino_server.tail_status
    flag.blank? ? DominoLog.new(@domino_server.id).do_tail : @domino_server.update_attribute(:tail_status, "")
    message = flag.blank? ? "Started Tail" : "Stopped Tail"

        respond_to do |format|
      format.html { redirect_to domino_servers_url, notice: message }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domino_server
      @domino_server = DominoServer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domino_server_params
      result=params.require(:domino_server).permit(:name, :ip, :ldap_treebase, :ldap_hostname, :ldap_port, :ldap_auth_method, :ldap_filter, :ldap_username, :ldap_pwd, :ssh_user, :ssh_pwd)
      #[:ssh_password,:ldap_password].each {|x| result.delete(x) if result[x].blank?}
      result
    end
end

app/helpers/domino_servers_helper.rb
module DominoServersHelper
end

app/views/domino_servers/_form.html.haml
- if @domino_server.errors.any?
  .row
  .col-lg-6
    .panel.panel-default
      .panel-heading
        Errors
      / /.panel-heading
      .panel-body
        .alert.alert-success
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          = succeed "." do
            %a.alert-link{:href => "#"} Alert Link
        .alert.alert-info
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          = succeed "." do
            %a.alert-link{:href => "#"} Alert Link
        .alert.alert-warning
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          = succeed "." do
            %a.alert-link{:href => "#"} Alert Link
        .alert.alert-danger
          = "#{pluralize(@domino_server.errors.count, "error")} prohibited this domino_server from being saved:"
          %ul
            - @domino_server.errors.full_messages.each do |msg|
              %li= msg
          = succeed "." do
            %a.alert-link{:href => "#"} Alert Link
      / .panel-body
    / /.panel
  / /.col-lg-6
.panel-body
  .row
    .col-lg-6
      = form_for @domino_server, role: "form" do |f|
        .form-group
          = f.label :name
          = f.text_field :name , class: "form-control"
          %p.help-block Mnemonical server name.
        .form-group
          = f.label :ip
          = f.text_field :ip, class: "form-control", :placeholder => "IP or Hostname of server"
          %p.help-block Ip or Hostname of domino server.

        .form-group
          = f.label :ldap_hostname
          = f.text_field "ldap_hostname", class: "form-control", :placeholder => "IP of LDAP server"
          %p.help-block Ip or Hostname of LDAP server.
        .form-group
          = f.label :ldap_port
          = f.text_field "ldap_port", class: "form-control", :placeholder => "port of  LDAP server"

        .form-group
          = f.label :ldap_treebase
          = f.text_field "ldap_treebase", class: "form-control", :placeholder => "treebase"
          %p.help-block treebase. example: ou=OrganizationUnit,dc=Domain,C=IT
        .form-group
          = f.label :ldap_filter
          = f.text_field "ldap_filter", class: "form-control", :placeholder => "filter"
          %p.help-block filter. example: (mail=*)
        .form-group
          = f.label :ldap_username
          = f.text_field "ldap_username", class: "form-control", :placeholder => "username"

        .form-group
          = f.label :ldap_pwd
          = text_field_tag "domino_server[ldap_pwd]","",class: "form-control", :placeholder => "password" , type: "password"


        .form-group
          = f.label :ssh_user
          = f.text_field :ssh_user, class: "form-control", :placeholder => "username"
        .form-group
          = f.label :ssh_pwd
          = text_field_tag "domino_server[ssh_pwd]","",class: "form-control", :placeholder => "password" , type: "password"

        %button.btn.btn-success{:type => "submit"} Save

app/views/domino_servers/edit.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Editing domino_server

= render 'form'

app/views/domino_servers/index.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Domino Servers
      / /.panel-heading
      .panel-body
        .table-responsive
          %table#dataTables-example.table.table-striped.table-bordered.table-hover
            %thead
              %tr
                %th Server Name
                %th IP Address
                %th LDAP Address
                %th Actions

            %tbody
              - @domino_servers.each do |domino_server|
                %tr.odd.gradeX
                  %td=domino_server.name
                  %td=domino_server.ip
                  %td="#{domino_server.ldap_hostname}:#{domino_server.ldap_port}"
                  %td
                    =link_to domino_server, class: "", title: "Show" do
                      %i.fa.fa-search.fa-fw
                    =link_to load_names_entry_domino_server_path(domino_server), method: :post, class: "", title: "Reload Names Entry" do
                      %i.fa.fa-cog.fa-fw
                    =link_to tail_domino_server_path(domino_server), method: :post, class: "", title: domino_server.tail_status do
                      -if domino_server.tail_status.blank?
                        %i.fa.fa-play.fa-fw
                      -else
                        %i.fa.fa-stop.fa-fw
                    =link_to edit_domino_server_path(domino_server), class: "", title: "Edit" do
                      %i.fa.fa-pencil.fa-fw
                    =link_to domino_server, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "" , title: "Destroy" do
                      %i.fa.fa-trash-o.fa-fw

        / /.table-responsive
/ Page-Level Demo Scripts - Tables - Use for reference
:javascript
  $(document).ready(function() {
      $('#dataTables-example').dataTable();
  });

app/views/domino_servers/new.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        New Domino Server

= render 'form'

app/views/domino_servers/show.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        Domino Server

= render 'form'